# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savedNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('valueCalories', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
