# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_AddProfileModel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='weight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
