# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_UserProfileModel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='age',
        ),
    ]
