# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_AddBMI'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='dob',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
