# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofilemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
