# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180426_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
