# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20180309_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
