# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20180413_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='goal',
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='body',
        ),
        migrations.AddField(
            model_name='goal',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
