# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savednutrition',
            name='servingUnit',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='savednutrition',
            name='itemName',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
